# Replace things between square brackets
STARDOG_GROUP1_ENDPOINT = 'http://[IP ADDRESS]:5820/[GROUP 1 DATABASE NAME]/query'
STARDOG_WIKI_ENDPOINT = 'http://[IP ADDRESS]:5820/[WIKITAAABLE DATABASE NAME]/query'
STARDOG_USERNAME = '[USERNAME]'
STARDOG_PASSWORD = '[PASSWORD]'
